version: 1
disable_existing_loggers: false

formatters:
  simple:
    format: "[%(levelname)s] %(message)s"
  detailed:
    format: "%(asctime)s | %(levelname)-8s | %(name)s | %(filename)s:%(lineno)d | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    maxBytes: 1048576
    backupCount: 5
    encoding: utf-8
  backup:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    maxBytes: 1048576
    backupCount: 5
    encoding: utf-8

loggers:
  PSO:
    level: DEBUG
    handlers:
      - console
      - file
      - backup
    propagate: no
